
name: Mirror to Gitopia

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Gitopia mirror
        uses: gitopia/gitopia-mirror-action@v0.5.0
        with:
          gitopiaWallet: "${{ secrets.koa }}"
          remoteUrl: "gitopia://gitopia1f26h7c8l8uvx8way8vtyyzjnv2dladwfrfcdl7/1-KOA"

